### ISSUE TITLE
what if some Deployment PODS do not want to inject kum-init sidecar,how to set?

### ISSUE THREAD

**Issue by huangkaiyan10** [kumahq/kuma-demo#100]
apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  namespace: kuma-demo
  annotations:
    kuma.io/sidecar-injection: enabled

---------------
 By default we set the namespace and add the annotation kuma.io/sidecar-injection: enabled so that each POD of the k8s namespace  is injected kum-init sidecar. But what if some Deployment PODS do not want to inject kum-init sidecar,how to set?

**Comment by tharun208** [comment]
Hi, It is available in docs - https://kuma.io/docs/1.0.1/documentation/dps-and-data-model/#kubernetes

**Comment by huangkaiyan10** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kuma-example
spec:
  ...
  template:
    metadata:
      ...
      annotations:
        # indicate to Kuma that this Pod doesn't need a sidecar
        kuma.io/sidecar-injection: disabled
    spec:
      containers:
