### ISSUE TITLE
how to set a global traffic permission so that k8s namespace pods cannot access k8s namespace pods

### ISSUE THREAD

**Issue by huangkaiyan10** [kumahq/kuma-demo#101]
how to set a global traffic permission so that k8s namespace pods cannot access k8s namespace pods ，pods of A k8s namespace cannot access pods of B k8s namespace 。how to set in k8s yml file 

--------------
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: allow-all-traffic
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'

**Comment by michaelbeaumont** [comment]
Closing this, you should be able to use [autogenerated k8s tags](https://kuma.io/docs/dev/explore/dpp-on-kubernetes/#tag-generation) with `TrafficPermission`.
