### ISSUE TITLE
Missing explanation of what demo does

### ISSUE THREAD

**Issue by aaronhmiller** [kumahq/kuma-demo#72]
**Describe the bug**
No explanation of what the demo does or why that's useful.

**To Reproduce**
1. Read the README
2. Find no explanation of what the demo is supposed to show and why that is important.

**Expected behavior**
A great demo explains a problem and shows the user how the software fixes that problem.

**Screenshots**

**Desktop (please complete the following information):**
 - Kuma: [e.g. v0.3.1]
 - Environment [e.g. Kubernetes, Universal]

**Additional context**

**Comment by michaelbeaumont** [comment]
There's a lot of information in the README now about the demo application.
