### ISSUE TITLE
How do I use kuma on the intranet that Can't connect to the internet . Because DP (data-plane) dynamically inject into my services pod, I cannot set up to pull DP (data-plane) docker images from my private mirror warehouse harbor.

### ISSUE THREAD

**Issue by huangkaiyan10** [kumahq/kuma-demo#95]
How do I use kuma on the intranet that Can't connect to the internet . Because DP (data-plane) dynamically inject into my services pod, I cannot set up to pull DP (data-plane) docker images from my private mirror warehouse harbor.

**Comment by huangkaiyan10** [comment]
I want install kuma on  k8s(kubernetes)

**Comment by nickolaev** [comment]
Checke [`docker save`](https://docs.docker.com/engine/reference/commandline/save/) and [`docker load`](https://docs.docker.com/engine/reference/commandline/load/)

**Comment by huangkaiyan10** [comment]
> Please check [`docker save`](https://docs.docker.com/engine/reference/commandline/save/) and [`docker load`](https://docs.docker.com/engine/reference/commandline/load/).

That's one way to do it.

**Comment by huangkaiyan10** [comment]
Can you guys install kuma in kubernetesan by publishing yaml so that I can change the docker images in yaml to my hardor docker images?

**Comment by nickolaev** [comment]
`kumactl install control-plane > kuma_install.yaml` this is how you got the yaml manifest.

**Comment by jakubdyszkiewicz** [comment]
Hey @huangkaiyan10 you can modify image names with kumactl arguments. Try `kumactl install control-plane --help` to see all the options

**Comment by huangkaiyan10** [comment]
thank you

**Comment by devadvocado** [comment]
Will close this issue first, @huangkaiyan10. If you have any additional questions, feel free to  join our [Slack](http://chat.kuma.io/)!
